In [5]:
import numpy as np

def rbf_kernel(x, y, sigma=1.0):

    diff = x - y    
    squared_distance = np.dot(diff, diff) 

    kernel_value = np.exp(-squared_distance / (2 * sigma**2)) 
    
    return kernel_value

x = np.array([1, 3, 5])
y = np.array([2, 4, 6])

kernel_value = rbf_kernel(x, y, sigma=1.0)

print("RBF Kernel Value:", kernel_value)


RBF Kernel Value: 0.22313016014842982


In [6]:
import numpy as np

def compute_rbf_kernel_matrix(X, sigma=1.0):
   
    m = X.shape[0] 
    kernel_matrix = np.zeros((m, m)) 
    
    for i in range(m):
        for j in range(m):
     
            diff = X[i] - X[j]
            squared_distance = np.dot(diff, diff)
            
            kernel_matrix[i, j] = np.exp(-squared_distance / (2 * sigma**2))
    
    return kernel_matrix

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

sigma = 1.0
kernel_matrix = compute_rbf_kernel_matrix(X, sigma)

print("RBF Kernel Matrix:")
print(kernel_matrix)


RBF Kernel Matrix:
[[1.00000000e+00 1.37095909e-06 3.53262857e-24 1.71088354e-53]
 [1.37095909e-06 1.00000000e+00 1.37095909e-06 3.53262857e-24]
 [3.53262857e-24 1.37095909e-06 1.00000000e+00 1.37095909e-06]
 [1.71088354e-53 3.53262857e-24 1.37095909e-06 1.00000000e+00]]
